-- Migración 019: Agregar rol super_admin
-- Superadmin ve TODO sin restricciones
--
-- SIN EFECTO, A PROPÓSITO. No tocar.
--
-- Este archivo antes redefinía users_role_check para agregar 'super_admin'.
-- Como el runner re-ejecuta todo en cada `npm run migrate` y en orden de
-- nombre, esa redefinición era una bomba: 019 corría DESPUÉS de 023 pero con
-- una lista que NO incluía 'jefe_st', así que en una base con un jefe_st
-- el ADD CONSTRAINT fallaba y abortaba la corrida entera.
--
-- La lista de roles vive únicamente en 017_roles_and_permissions.sql.
-- Para agregar un rol, se edita esa lista y nada más.
