-- Migración 023: Rol Jefe de Servicio Técnico
-- Agrega el rol jefe_st para gestionar el módulo de servicio técnico
--
-- SIN EFECTO, A PROPÓSITO. No tocar.
--
-- Este archivo antes redefinía users_role_check para agregar 'jefe_st'.
-- La invocación era inocua solo por casualidad del orden de archivos; la causa
-- raíz era tener el mismo CHECK definido en tres migraciones distintas con
-- listas diferentes. Ahora la lista vive únicamente en
-- 017_roles_and_permissions.sql, y esta migración es un no-op explícito
-- para no romper el historial ni los entornos que ya la aplicaron.
